# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grSim_Commands.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import zss_cmd_pb2 as zss__cmd__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14grSim_Commands.proto\x1a\rzss_cmd.proto\"j\n\x0egrSim_Commands\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x14\n\x0cisteamyellow\x18\x02 \x01(\x08\x12/\n\x0erobot_commands\x18\x03 \x01(\x0b\x32\x17.ZSS.New.Robots_Commandb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grSim_Commands_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GRSIM_COMMANDS._serialized_start=39
  _GRSIM_COMMANDS._serialized_end=145
# @@protoc_insertion_point(module_scope)
