# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log_labeler_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import messages_robocup_ssl_wrapper_pb2 as messages__robocup__ssl__wrapper__pb2
import ssl_gc_referee_message_pb2 as ssl__gc__referee__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16log_labeler_data.proto\x1a\"messages_robocup_ssl_wrapper.proto\x1a\x1cssl_gc_referee_message.proto\"?\n\x0fLabelerMetadata\x12\x13\n\x0bnum_cameras\x18\x01 \x01(\r\x12\x17\n\x0fmessage_offsets\x18\x02 \x03(\x04\"y\n\x0cLabelerFrame\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12*\n\x0cvision_frame\x18\x02 \x01(\x0b\x32\x12.SSL_WrapperPacketH\x00\x12!\n\rreferee_frame\x18\x03 \x01(\x0b\x32\x08.RefereeH\x00\x42\x07\n\x05\x66rame\"2\n\x11LabelerFrameGroup\x12\x1d\n\x06\x66rames\x18\x01 \x03(\x0b\x32\r.LabelerFrameb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_labeler_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LABELERMETADATA._serialized_start=92
  _LABELERMETADATA._serialized_end=155
  _LABELERFRAME._serialized_start=157
  _LABELERFRAME._serialized_end=278
  _LABELERFRAMEGROUP._serialized_start=280
  _LABELERFRAMEGROUP._serialized_end=330
# @@protoc_insertion_point(module_scope)
