# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: selftunning_param_info.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cselftunning_param_info.proto\"L\n\x05Param\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x02\x12\x12\n\nlowerlimit\x18\x03 \x01(\x02\x12\x12\n\nupperlimit\x18\x04 \x01(\x02\"F\n\tparamInfo\x12\x15\n\x05param\x18\x01 \x03(\x0b\x32\x06.Param\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x13\n\x0b\x65nvironment\x18\x03 \x02(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'selftunning_param_info_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PARAM._serialized_start=32
  _PARAM._serialized_end=108
  _PARAMINFO._serialized_start=110
  _PARAMINFO._serialized_end=180
# @@protoc_insertion_point(module_scope)
