# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zss_rec.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import zss_geometry_pb2 as zss__geometry__pb2
import zss_debug_pb2 as zss__debug__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rzss_rec.proto\x12\x0cZSS.Protocol\x1a\x12zss_geometry.proto\x1a\x0fzss_debug.proto\"8\n\x0bRecMessages\x12)\n\x07recMsgs\x18\x01 \x03(\x0b\x32\x18.ZSS.Protocol.RecMessage\"\xe3\x01\n\nRecMessage\x12\r\n\x05\x63trlC\x18\x01 \x02(\x08\x12\x30\n\x0cselectedArea\x18\x02 \x02(\x0b\x32\x1a.ZSS.Protocol.SelectedArea\x12\x34\n\x0emaintainVision\x18\x03 \x02(\x0b\x32\x1c.ZSS.Protocol.MaintainVision\x12+\n\tdebugMsgs\x18\x04 \x03(\x0b\x32\x18.ZSS.Protocol.Debug_Msgs\x12\x31\n\x0f\x61thenaDebugMsgs\x18\x05 \x01(\x0b\x32\x18.ZSS.Protocol.Debug_Msgs\"F\n\x0cSelectedArea\x12\x0c\n\x04maxX\x18\x01 \x02(\x02\x12\x0c\n\x04maxY\x18\x02 \x02(\x02\x12\x0c\n\x04minX\x18\x03 \x02(\x02\x12\x0c\n\x04minY\x18\x04 \x02(\x02\"\xc0\x01\n\x0eMaintainVision\x12\x11\n\tlastTouch\x18\x01 \x02(\x05\x12\x15\n\rlastTouchTeam\x18\x02 \x02(\x05\x12.\n\nprocessMsg\x18\x03 \x03(\x0b\x32\x1a.ZSS.Protocol.TeamRobotMsg\x12,\n\x08maintain\x18\x04 \x03(\x0b\x32\x1a.ZSS.Protocol.TeamRobotMsg\x12&\n\x05\x62\x61lls\x18\x05 \x02(\x0b\x32\x17.ZSS.Protocol.Balls4Rec\"6\n\x0cTeamRobotMsg\x12&\n\x05robot\x18\x01 \x03(\x0b\x32\x17.ZSS.Protocol.Robot4Rec\"\xa1\x01\n\tRobot4Rec\x12\x0c\n\x04posX\x18\x01 \x02(\x01\x12\x0c\n\x04posY\x18\x02 \x02(\x01\x12\r\n\x05\x61ngle\x18\x03 \x02(\x01\x12\r\n\x05valid\x18\x04 \x02(\x08\x12\x0e\n\x06imuDir\x18\x05 \x02(\x01\x12\x12\n\nimucleaned\x18\x06 \x02(\x08\x12\x0f\n\x07\x62\x61ttery\x18\x07 \x02(\x01\x12\x13\n\x0b\x63\x61pacitance\x18\x08 \x02(\x01\x12\x10\n\x08infrared\x18\t \x01(\x08\"K\n\tBalls4Rec\x12\x0c\n\x04size\x18\x01 \x02(\x05\x12!\n\x04\x62\x61ll\x18\x02 \x03(\x0b\x32\x13.ZSS.Protocol.Point\x12\r\n\x05valid\x18\x03 \x02(\x08')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zss_rec_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECMESSAGES._serialized_start=68
  _RECMESSAGES._serialized_end=124
  _RECMESSAGE._serialized_start=127
  _RECMESSAGE._serialized_end=354
  _SELECTEDAREA._serialized_start=356
  _SELECTEDAREA._serialized_end=426
  _MAINTAINVISION._serialized_start=429
  _MAINTAINVISION._serialized_end=621
  _TEAMROBOTMSG._serialized_start=623
  _TEAMROBOTMSG._serialized_end=677
  _ROBOT4REC._serialized_start=680
  _ROBOT4REC._serialized_end=841
  _BALLS4REC._serialized_start=843
  _BALLS4REC._serialized_end=918
# @@protoc_insertion_point(module_scope)
