# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zss_kickparam.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13zss_kickparam.proto\x12\x0cZSS.Protocol\"\x8b\x01\n\x0bRobot_Param\x12\"\n\x05robot\x18\x01 \x02(\x0b\x32\x13.ZSS.Protocol.Robot\x12+\n\tchipparam\x18\x02 \x02(\x0b\x32\x18.ZSS.Protocol.Chip_Param\x12+\n\tflatparam\x18\x03 \x02(\x0b\x32\x18.ZSS.Protocol.Flat_Param\"L\n\nFlat_Param\x12\n\n\x02\x66\x61\x18\x01 \x02(\x01\x12\n\n\x02\x66\x62\x18\x02 \x02(\x01\x12\n\n\x02\x66\x63\x18\x03 \x02(\x01\x12\x0c\n\x04\x66max\x18\x04 \x02(\x01\x12\x0c\n\x04\x66min\x18\x05 \x02(\x01\"L\n\nChip_Param\x12\n\n\x02\x63\x61\x18\x01 \x02(\x01\x12\n\n\x02\x63\x62\x18\x02 \x02(\x01\x12\n\n\x02\x63\x63\x18\x03 \x02(\x01\x12\x0c\n\x04\x63max\x18\x04 \x02(\x01\x12\x0c\n\x04\x63min\x18\x05 \x02(\x01\"!\n\x05Robot\x12\x0c\n\x04team\x18\x01 \x02(\x05\x12\n\n\x02id\x18\x02 \x02(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zss_kickparam_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROBOT_PARAM._serialized_start=38
  _ROBOT_PARAM._serialized_end=177
  _FLAT_PARAM._serialized_start=179
  _FLAT_PARAM._serialized_end=255
  _CHIP_PARAM._serialized_start=257
  _CHIP_PARAM._serialized_end=333
  _ROBOT._serialized_start=335
  _ROBOT._serialized_end=368
# @@protoc_insertion_point(module_scope)
